version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres13
    environment:
      POSTGRES_USER: baek
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres -c max_prepared_transactions=640
               -c max_connections=3000

volumes:
  pgdata: